config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :photos, only: [:index, :destroy] do
      collection do
        post :upload
      end
    end

    resources :articles do
      collection do
        post :preview
        post :photos
      end
    end
  end

  resources :demos

  resources :articles do
    collection do
      get :search
      post :search
    end
  end

  resources :comments

  get '/admin', to: 'admin/articles#index'

  post '/signin', to: 'admin/sessions#create'
  get '/signin', to: 'admin/sessions#new'
  get '/signout', to: 'admin/sessions#destroy'

  get '/blog/rss', to: 'welcome#rss'
  get '/about', to: 'welcome#about'
  get '/photo', to: 'welcome#photo'
  root 'welcome#index'
end

app/models/article.rb
require 'markdown'
class Article < ActiveRecord::Base
  has_many :comments

  validates :title, :content, presence: true

  default_scope -> { where(self_info: false) }

  def self.self_info
    Article.unscoped.where(self_info: true).first || Article.create(title: '个人信息', content: '刘祯', self_info: true)
  end

  def short_title
    if title.length > 10
      title[0..10] + '...'
    else
      title
    end
  end

  def to_html
    self.content = content_html
    self
  end

  def content_html
    self.class.render_html(self.content)
  end

  def self.render_html(content)
    rd = CodeHTML.new
    md = Redcarpet::Markdown.new(rd, autolink: true, fenced_code_blocks: true)
    md.render(content)
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article

  validates :message, :username, :email, presence: true
  validates :username, length: { maximum: 20 }
  validates_format_of :email,:with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  mount_uploader :image, ImageUploader

  scope :photo_album, -> { where(photo_type: true) }

  def image_name
    image.file.filename
  end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
  layout 'admin'

  before_action do
    unless login?
      flash[:error] = '请先登录后再操作'
      redirect_to signin_path
    end
  end

  def photos
    @photo = Photo.new(image: params["Filedata"])
    @photo.save!
    render :text=> "![](#{@photo.image.url})"
  end

  def preview
    render plain: Article.render_html(params[:body] || "")
  end

  def index
    @articles = Article.all.order(created_at: 'desc').page params[:page]
  end

  def edit
    @article = Article.unscoped.find(params[:id])
  end

  def update
    @article = Article.unscoped.find(params[:id])
    @article.update(article_params)
    if @article.self_info
      redirect_to admin_articles_path
    else
      redirect_to @article.to_html
    end
  end

  def new
    @article = Article.new
  end

  def show
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article.to_html
    else
      flash.now[:error] = '新增博客失败'
      render :new
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to admin_articles_path
  end

  private
  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/controllers/admin/photos_controller.rb
class Admin::PhotosController < ApplicationController
  layout 'admin'

  def index
    @photos = Photo.photo_album.order(created_at: 'desc').page params[:page]
  end

  def upload
    @photo = Photo.new(image: params['Filedata'], photo_type: true)
    @photo.save!
    render json: {status: 'ok'}
  end

  def destroy
    @photo = Photo.find(params[:id])
    if @photo.destroy
      flash[:success] = '删除成功'
    else
      flash[:error] = '删除失败'
    end
    redirect_to admin_photos_path
  end
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < ApplicationController
  layout 'admin'

  def new
  end

  def create
    if params[:session][:username] == ENV['pusher_user'] && params[:session][:password] == ENV['pusher_pwd']
      session[:login] = true
      redirect_to admin_articles_path
    else
      flash.now[:error] = '用户名或密码错误'
      render 'new'
    end
  end

  def destroy
    session[:login] = false
    flash[:notic] = '成功退出'
    redirect_to signin_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action do
    @newest_articles = Article.order(created_at: 'desc').limit(10)
  end

  helper_method :login?
  def login?
    session[:login].present?
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
    @meta_description = 'Rina\'s 所有博客文章.'
  end

  def show
    @article = Article.find(params[:id]).to_html
    @comment = Comment.new
    @comments = @article.comments.order(created_at: :desc)
  end

  def search
    params[:page] = 1 if params[:page].blank?
    @articles = Article.where("title like ? OR content like ?", "%#{params[:search]}%", "%#{params[:search]}%")
    @articles = @articles.page params[:page]
    if @articles.blank?
      flash.now[:error] = '没有你要找的内容'
      return
    end
    @articles.map do |a|
      a.title = a.title.gsub(params[:search].to_s, "<em>#{params[:search]}</em>")
      unless a.content.include?('/uploads/photo/image')
        a.content = a.content.gsub(params[:search].to_s, "<em>#{params[:search]}</em>")
      end
      htmlstring = TruncateHtml::HtmlString.new(a.to_html.content)
      a.content = TruncateHtml::HtmlTruncator.new(htmlstring).truncate
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
  end

  def create
    @article = Article.find(params[:article_id]).to_html
    @comment = Comment.new(comment_params.merge(article_id: params[:article_id]))
    @comments = @article.comments.order(created_at: :desc)
    if !@comment.save
      flash[:error] = '添加评论失败'
      render 'articles/show'
    else
      flash[:notic] = '添加评论成功'
      redirect_to @article
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:message, :username, :email)
  end
end

app/controllers/demos_controller.rb
class DemosController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @articles = Article.all.order(created_at: :desc).limit(8)
    @meta_description = 'Rina\'s 个人博客, 分享生活, 工作与技术的相关文章'
  end

  def rss
    @articles = Article.all.order(created_at: :desc).limit(10)
    render :layout=>false
    response.headers["Content-Type"] = "application/xml; charset=utf-8"
  end

  def about
    @self_info = Article.self_info
    @meta_description = 'Rina\'s 个人信息, 关于工作经历及个人简介.'
  end

  def photo
    @photos = Photo.photo_album
    flash[:notic] = '主人还未上传相片' if @photos.blank?
    render :layout=>'photo'
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/articles/_form.html.slim
= form_for [:admin, @article] do |f|
  = render 'shared/form_error_message'
  p.article-title
    = f.label '标题'
    = f.text_field :title
  .tabbable.tabs-left
    ul.nav.nav-tabs
      li.content-title.active
        = link_to '内容', '#'
      li.preview-title
        = link_to '预览', '#'
      a.pull-right#upload-photo herf='#'
        |插入图片
      input.file-window type='file'
    = f.text_area :content
    .markdown-body.markdown
  = f.submit '发表'
  .pull-right
    = link_to '排版说明', 'https://ruby-china.org/markdown', target: '_blank'

app/views/admin/articles/edit.html.slim
.container
  h2.article-new
    |编辑博客

  = render 'form'

app/views/admin/articles/index.html.slim
.container
  - @articles.each do |article|
    .row
      .col-md-3
        = link_to article.title, article
      .col-md-2
        = article.created_at.to_date
      .col-md-1
        = link_to "评论", article
      .col-md-1
        = link_to "编辑", edit_admin_article_path(article)
      .col-md-1
        = link_to "删除", admin_article_path(article), method: :delete, data: { confirm: "确认删除?" }

  = paginate @articles

app/views/admin/articles/new.html.slim
.container
  h2.article-new
    |新建博客

  = render 'form'

app/views/admin/photos/index.html.slim
.container
  .row
    a.pull-right.btn.btn-info.index-btn-info.self_photograph#upload-photo-album herf='#'
      |插入图片
    input.file-window-photo-album type='file'

  - @photos.each do |photo|
    .row
      .col-md-2
        = photo.image_name
      .col-md-3
        = image_tag photo.image_url, style: 'width: 50%'
      .col-md-2
        = photo.created_at.to_date
      .col-md-1
        = link_to "删除", admin_photo_path(photo), method: :delete, data: { confirm: "确认删除?" }

  = paginate @photos

app/views/articles/index.html.slim
- content_for(:title) do
  |所有 - 所有文章列表

- @articles.each do |article|
  .row.all-article
    .col-md-4
      = link_to article.title, article
    .col-md-4
      = article.created_at.to_date

app/views/articles/search.html.slim
.search-content
  = render 'shared/form_error_message'
  - @articles.each do |article|
    h2.search-title
      = link_to sanitize(article.title), article
    .search-html
      = sanitize article.content
  = paginate @articles

app/views/articles/show.html.slim
h2.rina-title
  = @article.title
.content.markdown
  == @article.content_html

.create-comment
  = render 'shared/form_error_message'

  = form_for @comment, url: comments_path(article_id: @article.id) do |f|
    .form-group
      = f.text_area :message, rows: '3', class: 'form-control', placeholder: '留言...'
    .form-group
      = f.text_field :username, class: 'form-control form-comment', placeholder: '你的名字'
    .form-group
      = f.text_field :email, class: 'form-control form-comment', placeholder: '邮箱'
    .form-group
      = f.submit '提交', class: 'btn btn-default'

.form-group
  - @comments.each_with_index do |comment, index|
    - if index == 0
      .comment-diag
    .comment-wrapper
      p.name
        = comment.username
        |•
        span.created-at
          = comment.created_at.strftime("%Y-%m-%d %H:%M")
      p.comment-content
        = comment.message

.jiathis_style
  a.jiathis_button_tools_1
  a.jiathis_button_tools_2
  a.jiathis_button_tools_3
  a.jiathis_button_linkedin
  a.jiathis_button_tools_4
  a.jiathis_counter_style

javascript:
  var jiathis_config = {
    appkey:{
      "tpeople":"6045604360"
    },
    "do_not_track":true,
    "ralateuid":{"tsina":"1647863564"},
    "data_track_clickback":true
  };

script type="text/javascript" src="http://v3.jiathis.com/code/jia.js?uid=1" charset="utf-8"

app/views/demos/index.html.slim
p 敬请期待

app/views/layouts/admin.html.slim
html
  head
    title
      | Rina's Blog
    meta name='viewport' content="width=device-width, initial-scale=1.0, max-scale=1.0"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    nav.navbar.navbar-inverse.rina-admin-navbar
      .container-fluid
        .navbar-header
          button.navbar-toggle.collapsed type='button' data-toggle='collapse' data-target='#bs-example-navbar-collapse-1'
            span.sr-only
              | Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          = link_to 'Rina', admin_articles_path, class: 'navbar-brand rina-logo'

        .collapse.navbar-collapse#bs-example-navbar-collapse-1
          ul.nav.navbar-nav
            li = link_to '创建博客', new_admin_article_path
            li = link_to '博客管理', admin_articles_path
            li = link_to '相册管理', admin_photos_path
            li = link_to '个人资料', edit_admin_article_path(Article.self_info)
          ul.nav.navbar-nav.navbar-right
            li= link_to '返回首页', '/'
            - if login?
              li = link_to '退出', '/signout'
    = yield

app/views/layouts/application.html.slim
html
  head
    title
      - if content_for?(:title)
        = yield(:title)
      - else
        |Rina's Blog

    meta name='description' content="#{@meta_description}"
    meta name='viewport' content="width=device-width, initial-scale=1.0, max-scale=1.0"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = javascript_include_tag 'mp3'
    = csrf_meta_tags
  body
    .container
      .row.rina-header
        .col-sm-4
          .ih-item.circle.effect15.left_to_right.header-circle
            = link_to '#' do
              .img
                = image_tag('7.jpg')
              .info
                h3 Music box
                p.start-misic Click to Start
                p.stop-misic style='display:none' Click to Stop
          = audio_tag("sound.mp3", loop: true, class: 'audio-tag', type: 'audio/mpeg')
          = link_to 'https://github.com/liuzhenangel/Rina_Blog', target: '_blank' do
            = image_tag('fork_me_on_github.png', class: 'fork_me_on_github')
        .col-sm-8.index-navbar-right
          =link_to '订阅', '/blog/rss', class: 'btn btn-info index-btn-info a'
          =link_to '主页', '/', class: 'btn btn-info index-btn-info a'
          =link_to '所有', articles_path, class: 'btn btn-info index-btn-info a'
          =link_to '相册', '/photo', class: 'btn btn-info index-btn-info a'
          //=link_to 'Demo', demos_path, class: 'btn btn-info index-btn-info a'
          =link_to '关于', '/about', class: 'btn btn-info index-btn-info a'
      .row
        .col-md-9
          = yield
        .col-md-3
          .search-field
            = form_for(:search, url: search_articles_path, method: 'get') do |f|
              = text_field_tag 'search', params[:search], class: 'form-control', placeholder: 'Search'
          ul.nav.rina-new-article
            li
              h3.widgettitle 最新文章
            - @newest_articles.each do |article|
              li.rina-new-title
                = link_to article.short_title, article_path(article)
      .page-footer
        span.link liuzhen.me
        span.time © 2015 - 2015
        .license
          span
            = link_to 'Rina\'s Blog', 'https://github.com/liuzhenangel/Rina_Blog', target: '_blank'

app/views/layouts/photo.html.slim
html
  head
    title
      |Rina's Blog
    meta name="viewport" content="width=device-width, initial-scale=1.0, max-scale=1.0"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body.photo-body
    .container.photo-container
      = audio_tag("sound.mp3", loop: true, class: 'audio-tag', type: 'audio/mpeg')
      = yield

app/views/shared/_form_error_message.html.slim
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-dismissible alert-#{name == 'error'? 'danger':'info'}" role='alert'
      button.close type='button' data-dismiss="alert" aria-label="Close"
        span aria-hidden="true"
          |&times;
      = msg

app/views/welcome/about.html.slim
- content_for(:title) do
  |关于 - 个人资料

h2
  = @self_info.title
.show-background
  .content.markdown
    == @self_info.content_html

app/views/welcome/index.html.slim
- content_for(:title) do
  |主页 - 最新文章列表
.row.index-row
  - @articles.each_with_index do |artc1, index|
    .col-sm-6
      .ih-item.square.effect3.bottom_to_top.index-row
        .index-title
          = artc1.title
        = link_to article_path(artc1) do
          .img
            = image_tag("#{index + 1}.jpg")
          .info
            h3 = artc1.title
            p.square-p 点击查看

app/views/welcome/photo.html.slim
= render 'shared/form_error_message'

section
  .title
    button.start.action type="button" Play
    button.stop.action type="button" Stop
  .slider-wrap
    .slider
      - @photos.each do |photo|
        = image_tag(photo.image_url, size: '940*400')
        p = photo.image_name
footer
  = link_to '返回首页', '/'